### ISSUE TITLE
"Annual Enrollment of Undergraduate Majors in BS in Computer Science" table appears twice

### ISSUE THREAD

**Issue by stchang** [umbcs/umbcs.github.io#3]
in the page here: https://www.cs.umb.edu/cs_bs

There appear to be two tables labeled "Annual Enrollment of Undergraduate Majors in BS in Computer Science"

I think the second one should be "Annual Number of BS degrees awarded in Computer Science (Five-Year Trend)"?
( from looking here: https://www.umb.edu/academics/csm/computer_science/ug/computer_science_bs)

**Comment by haehn** [comment]
Great catch! @stchang can you send a pull request?

**Comment by haehn** [comment]
fixed by @stchang !
